### ISSUE TITLE
location of gup does not exists

### ISSUE THREAD

**Issue by eelcocramer** [nao1215/homebrew-tap#1]
Updating, installing through `brew` does not work. The download url gives does not exsist (404).

Alternatively you can make brew build the binary by using the following formula (for the current latest version):

```ruby
class Gup < Formula
  desc "Update binaries installed by 'go install' with goroutines."
  homepage "https://github.com/nao1215/gup"
  url "https://github.com/nao1215/gup.git",
    tag: "v0.24.3",
    revision: "9f86d80c9f12949a94c2751b53b62fa70ea7d5ed"
  sha256 "f10deca48d1de65f0eb3198ce215ab7a7256f3e78055a430f4bb7347ee03e2ac"
  license "Apache License 2.0"
  head "https://github.com/nao1215/gup.git", branch: "main"

  bottle do
  end

  depends_on "go" => :build

  def install
    ldflags = %W[
      -s -w
      -X github.com/nao1215/gup/internal/cmdinfo.Version=#{version}
    ]

    system "go", "build", *std_go_args(ldflags:)
  end

  test do
    assert_match "gup version #{version.to_s} (under Apache License version 2.0)", shell_output("#{bin}/gup version 2>&1")
  end
end
```

**Comment by nao1215** [comment]
@eelcocramer 
Thank you for your report.
I have adopted your proposal. However, I don't have a Mac. So, I will test it at my company.

**Comment by eelcocramer** [comment]
Thank you for looking into it. The nice thing of my proposal is that it builds locally so it will work on both MacOS and Linux regardless of the processor architecture. 

It would be nice when homebrew would add bottles / precompiled versions. I'm not sure how this process goes but it would probably involve adding the recipe to their repository rather than using a tap.

**Comment by nao1215** [comment]
I am a Linux user. I just learned about the functionality of "brew" that you pointed out (local build) for the first time. It's very convenient, isn't it? I'll try to improve it when I find the opportunity next time.
